### ISSUE TITLE
please show node version

### ISSUE THREAD

**Issue by yoshimaa** [mixi-inc/JavaScriptTraining#28]
hi, thanks awesome tutorial!
im new to javascript.
i get some error when install latest node.
i resolved it, but someone may face some problem.
if it is a target for a beginner, please show!
if it does not need , tell me that reason.
then ill delete this issue. 
thanks:)

**Comment by Kuniwak** [comment]
Thanks, @yoshimaa .

> if it is a target for a beginner, please show!

Yes! we provide the training for beginners. :smiley:

I checked this training on Node.js v0.10.26 and v4.1.0.
I confirmed that this issue is NOT caused by Node.js version, but I found ESLint related problems caused by [the issue](https://github.com/eslint/eslint/pull/2179).

I resolved the issue and released it.
And started to use `npm shrinkwrap` to avoid similar problems.
This command is useful to peg dependencies.

If you have a question about how to apply the changes, please ask me!
Thanks! :smile:

**Comment by yoshimaa** [comment]
thanks to teach me the details, @Kuniwak!
i appreciate to you:D
